site_name: 'Language-based Security'
site_author: 'Deian Stefan'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/PLSysSec/cse291-winter18'
    - type: 'twitter'
      link: 'https://twitter.com/deiandelmars'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - css/extra.css

pages:
  - About: index.md
  - Syllabus: syllabus.md
  - Organization: about.md
  - Contact information: contact.md
  - Project ideas: ideas.md

